version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    assignees:
      - dmage
  - package-ecosystem: gomod
    directory: /config-tool
    schedule:
      interval: weekly
    groups:
      k8s:
        patterns:
          - k8s.io/*
          - sigs.k8s.io/*
  - package-ecosystem: npm
    directory: /config-tool/pkg/lib/editor
    schedule:
      interval: weekly
    assignees:
      - dmage
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    assignees:
      - dmage
