[tool.black]
line-length = 100
target-version = ['py39']

[tool.isort]
profile = "black"
known_local_folder = "auth,avatars,buildman,buildtrigger,data,digest,endpoints,features,health,image,notifications,oauth,proxy,storage,test,tools,util,workers,_init,active_migration,app,config,external_libraries,initdb,path_converters,release"

[tool.pylint.messages_control]
disable = "missing-docstring,invalid-name,too-many-locals,too-few-public-methods,too-many-lines"

[tool.pylint.typecheck]
ignored-modules = "features,greenlet"
generated-members = "REQUEST,acl_users,aq_parent,DoesNotExist,id,can"

[tool.pylint.format]
max-line-length = 100

[tool.coverage.run]
branch = true

[tool.coverage.report]
omit = ['test/**', 'venv/**', '**/test/**']

[tool.pyright]
stubPath = 'mypy_stubs'
